name: scrape

on:
  push:
    branches:
    - main
      
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.10'
      
      - name: Install Chrome
        run: |
          sudo wget http://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Install chromedriver
        run: |
          CHROME_VERSION=$(curl "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE")
          curl -Lo chromedriver-linux64.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          sudo apt install unzip
          mkdir chromedriver
          unzip -q "chromedriver-linux64.zip" -d "chromedriver"
          echo 'export PATH=$PATH:$(pwd)/chromedriver' >> ~/.bash_profile
          source ~/.bash_profile

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run scraper script
        run: |
          CHROME_VERSION=$(google-chrome --product-version) && echo $CHROME_VERSION
          python script.py

      - name: Commit and push changes
        id: commit_and_push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: "action: update car data"
          default_author: github_actions
      
      # - name: Get sha of latest commit and send notification
      #   run: >
      #     curl 
      #     -H "Title: Car Repo Scraper" 
      #     -H "Tags: car" 
      #     -H "Click: https://github.com/sphars/car-repo-scraper/commit/${{ steps.commit_and_push.outputs.commit_sha }}/" 
      #     -d "Data updated" 
      #     ntfy.sh/utah-car-repos
