name: scrape

on:
  push:
    branches:
    - main
      
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run scraper script
        run: python script.py

      - name: Commit and push changes
        id: commit_and_push
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "action: update car data"
          default_author: github_actions
      
      # - name: Get sha of latest commit and send notification
      #   run: >
      #     curl 
      #     -H "Title: Car Repo Scraper" 
      #     -H "Tags: car" 
      #     -H "Click: https://github.com/sphars/car-repo-scraper/commit/${{ steps.commit_and_push.outputs.commit_sha }}/" 
      #     -d "Data updated" 
      #     ntfy.sh/utah-car-repos
